version: '3'
services:
  graphql:
    image: app
    command: npm run dev
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    links:
      - dynamodb
    depends_on:
      - dynamodb
    environment:
      - AWS_DYNAMODB_REGION=localhost
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb:8000
  dynamodb:
    build: .
    image: app
    command: npm run dynamodb
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
    expose: 
      - "8000"
